const API="/api/v1";
const demoUsers={
 "engineer@terrasync.demo":{password:"demo123",name:"Bogere Francis",role:"Field Engineer",inspector_no:"FE-UG-0241",company:"Netis",phone:"+256 700 000 241",email:"engineer@terrasync.demo",certifications:[{name:"Certified Rigger",id:"CR-UG-2026-241",expires:"2027-06-30"},{name:"Tower Climbing & Rescue",id:"TCR-241",expires:"2027-02-15"}]},
 "coordinator@terrasync.demo":{password:"demo123",name:"Sarah Namuli",role:"Coordinator",inspector_no:"CO-UG-0042",company:"TerraSync Demo",phone:"+256 700 000 042",email:"coordinator@terrasync.demo",certifications:[{name:"Inspection Review Lead",id:"IRL-042",expires:"2028-01-31"}]},
 "admin@terrasync.demo":{password:"demo123",name:"System Administrator",role:"Administrator",inspector_no:"ADM-001",company:"TerraSync",phone:"+256 700 000 001",email:"admin@terrasync.demo",certifications:[{name:"Platform Administrator",id:"ADM-001",expires:"2029-01-01"}]}
};
let currentUser=null, cameraStream=null, assetCameraStream=null, capturedEvidence=null, capturedAssetEvidence=null;
const state={
 workOrders:[],sites:[],reports:[],
 outbox:JSON.parse(localStorage.getItem("terrasync_outbox")||"[]"),
 assets:JSON.parse(localStorage.getItem("terrasync_assets")||"[]")
};
const titles={dashboard:["Operations","Dashboard"],assignments:["Field work","Assignments"],inspect:["Capture","New inspection"],inventory:["Assets","Equipment inventory"],reports:["Reporting","Reports"],review:["Quality","AI review"],profile:["Account","Profile"]};

function saveAssets(){localStorage.setItem("terrasync_assets",JSON.stringify(state.assets));renderAssets();}
function saveOutbox(){localStorage.setItem("terrasync_outbox",JSON.stringify(state.outbox));renderStats();}
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;}
function deviceId(){let id=localStorage.getItem("terrasync_device_id");if(!id){id=uid();localStorage.setItem("terrasync_device_id",id)}return id;}
function initials(name){return name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();}
function setNetwork(){const e=document.getElementById("networkBadge");e.textContent=navigator.onLine?"● Online":"● Offline";e.className=`network ${navigator.onLine?"online":"offline"}`;}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll("#mainNav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.getElementById("pageEyebrow").textContent=titles[id][0];document.getElementById("pageTitle").textContent=titles[id][1];if(id!=="inspect")stopCamera();if(id!=="inventory")stopAssetCamera();}
async function api(path,opts={}){const r=await fetch(`${API}${path}`,{headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts});if(!r.ok)throw new Error(await r.text());return r;}
async function loadData(){if(!navigator.onLine){renderAll();return}const [w,s,r]=await Promise.all([api("/work-orders"),api("/sites"),api("/reports")]);state.workOrders=await w.json();state.sites=await s.json();state.reports=await r.json();localStorage.setItem("terrasync_workorders",JSON.stringify(state.workOrders));localStorage.setItem("terrasync_sites",JSON.stringify(state.sites));localStorage.setItem("terrasync_reports",JSON.stringify(state.reports));seedAssets();renderAll();}
function hydrate(){state.workOrders=JSON.parse(localStorage.getItem("terrasync_workorders")||"[]");state.sites=JSON.parse(localStorage.getItem("terrasync_sites")||"[]");state.reports=JSON.parse(localStorage.getItem("terrasync_reports")||"[]");seedAssets();renderAll();}
function seedAssets(){if(state.assets.length)return;state.assets=[
 {id:uid(),type:"RRU",manufacturer:"ZTE",model:"R8854",serial:"ZT-RRU-88241",quantity:3,height:"53 m",dimensions:"480 × 320 × 165 mm",condition:"Good",position:"Tower Leg B",source:"Client supplied"},
 {id:uid(),type:"Antenna",manufacturer:"Ace",model:"XXDW-65-33-iVT",serial:"ANT-608241-01",quantity:3,height:"49 m",dimensions:"1495 × 301 × 181 mm",condition:"Good",position:"Sector A/B/C",source:"Client supplied"},
 {id:uid(),type:"Microwave Dish",manufacturer:"Potevio",model:"HP2-23",serial:"MW-608241-04",quantity:1,height:"38 m",dimensions:"0.6 m",condition:"Fair",position:"Leg C",source:"Client supplied"}
];saveAssets();}
function renderAll(){populateWO();renderStats();renderAssignments();renderReports();renderReview();renderAssets();renderProfile();}
function populateWO(){const s=document.getElementById("workOrder");s.innerHTML=state.workOrders.map(w=>`<option value="${w.id}">${w.work_order_no} · ${w.report_type}</option>`).join("")}
function renderStats(){document.getElementById("assignmentCount").textContent=state.workOrders.length;document.getElementById("reportCount").textContent=state.reports.length;document.getElementById("riskCount").textContent=state.reports.filter(r=>r.ai_risk_score>=45).length;document.getElementById("queueCount").textContent=state.outbox.length;}
function renderAssignments(){const html=state.workOrders.map(w=>`<div class="list-row"><div><h4>${w.work_order_no}</h4><p>${w.report_type} · Site ${w.site_id}</p><span class="tag">Assigned</span></div><button data-start="${w.id}">Inspect</button></div>`).join("")||"<p class='muted'>No assignments.</p>";document.getElementById("assignmentList").innerHTML=html;document.getElementById("dashboardAssignments").innerHTML=html;}
function renderReports(){const queued=state.outbox.map(x=>({...x.payload,report_no:"Queued offline",status:"Queued",ai_risk_score:0,id:null}));const rows=[...queued,...state.reports];const html=rows.map(r=>`<div class="list-row"><div><h4>${r.report_no||"Local draft"}</h4><p>${r.report_type||""} · ${r.status||""}</p><p>${r.ai_summary||"Awaiting AI pre-screen"}</p></div><div><div class="${r.ai_risk_score>=45?"risk-high":r.ai_risk_score>=20?"risk-med":"risk-low"}">Risk ${r.ai_risk_score||0}/100</div>${r.id?`<a href="${API}/reports/${r.id}/pdf" target="_blank">PDF report</a>`:""}</div></div>`).join("")||"<p class='muted'>No reports.</p>";document.getElementById("reportsList").innerHTML=html;document.getElementById("dashboardReports").innerHTML=html;}
function renderReview(){const items=state.reports.slice().sort((a,b)=>(b.ai_risk_score||0)-(a.ai_risk_score||0));document.getElementById("reviewList").innerHTML=items.map(r=>`<div class="list-row"><div><h4>${r.report_no}</h4><p>${r.ai_summary||"No AI summary"}</p><span class="tag">${r.status}</span></div><div class="${r.ai_risk_score>=45?"risk-high":r.ai_risk_score>=20?"risk-med":"risk-low"}">${r.ai_risk_score||0}/100</div></div>`).join("")||"<p class='muted'>No reports awaiting review.</p>";}
function renderAssets(){document.getElementById("assetList").innerHTML=`<div class="asset-grid">${state.assets.map(a=>`<div class="asset-card"><div class="panel-head"><strong>${a.type}</strong><span class="tag">${a.condition}</span></div><p class="muted">${a.manufacturer||"—"} · ${a.model||"—"}</p><p>Serial: ${a.serial||"—"}<br>Qty: ${a.quantity||1}<br>Height: ${a.height||"—"}<br>Position: ${a.position||"—"}</p><span class="tag">${a.source||"On-site"}</span>${a.evidence?`<img src="data:${a.evidence.mime_type};base64,${a.evidence.content_base64}" alt="${a.type} evidence">`:""}</div>`).join("")}</div>`;}
function renderProfile(){if(!currentUser)return;document.getElementById("profileName").textContent=currentUser.name;document.getElementById("profileRole").textContent=currentUser.role;document.getElementById("profileInitials").textContent=initials(currentUser.name);document.getElementById("profileDetails").innerHTML=[["Inspector / staff no.",currentUser.inspector_no],["Company",currentUser.company],["Email",currentUser.email],["Phone",currentUser.phone]].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");document.getElementById("credentialList").innerHTML=currentUser.certifications.map(c=>`<div class="credential"><span>${c.id}</span><strong>${c.name}</strong><span>Valid to ${c.expires}</span></div>`).join("");}

function geolocate(){return new Promise((ok,fail)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(ok,e=>fail(new Error(e.message)),{enableHighAccuracy:true,timeout:15000,maximumAge:0}):fail(new Error("Geolocation unavailable")))}
function canvasBlob(c,q=.62){return new Promise((ok,fail)=>c.toBlob(b=>b?ok(b):fail(new Error("Image encoding failed")),"image/jpeg",q))}
function b64(blob){return new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(",")[1]);r.onerror=()=>fail(r.error);r.readAsDataURL(blob)})}
async function hash(blob){const h=await crypto.subtle.digest("SHA-256",await blob.arrayBuffer());return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function watermark(ctx,w,h,ts,lat,lon,acc){const s=Math.max(1,w/1200),pad=16*s,line=27*s,font=18*s,rows=[new Date(ts).toLocaleString(),`${lat.toFixed(6)}, ${lon.toFixed(6)}  ±${Math.round(acc)} m`];ctx.save();ctx.fillStyle="rgba(0,0,0,.62)";ctx.fillRect(0,h-(pad*2+rows.length*line),w,pad*2+rows.length*line);ctx.fillStyle="#fff";ctx.font=`600 ${font}px system-ui`;rows.forEach((t,i)=>ctx.fillText(t,pad,h-(pad+rows.length*line)+i*line));ctx.restore();}
async function makeEvidence(video,canvas){const p=await geolocate(),ts=new Date().toISOString(),max=1280,scale=Math.min(1,max/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);const ctx=canvas.getContext("2d");ctx.drawImage(video,0,0,canvas.width,canvas.height);watermark(ctx,canvas.width,canvas.height,ts,p.coords.latitude,p.coords.longitude,p.coords.accuracy);const blob=await canvasBlob(canvas,.58);return {kind:"photo",source:"live_camera",name:`evidence-${uid()}.jpg`,evidence_id:uid(),sha256:await hash(blob),mime_type:"image/jpeg",content_base64:await b64(blob),captured_at:ts,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,device_id:deviceId(),inspector_name:currentUser.name,work_order_no:document.getElementById("workOrder").selectedOptions[0]?.textContent||"ON-SITE-ASSET"};}

async function openCam(video,which){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});if(which==="inspection")cameraStream=stream;else assetCameraStream=stream;video.srcObject=stream;video.hidden=false;await video.play();return true}catch(e){alert(`Camera permission is required: ${e.message}`);return false}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}}
function stopAssetCamera(){if(assetCameraStream){assetCameraStream.getTracks().forEach(t=>t.stop());assetCameraStream=null}}

document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();const email=document.getElementById("loginEmail").value.trim().toLowerCase(),pw=document.getElementById("loginPassword").value,u=demoUsers[email];if(!u||u.password!==pw){document.getElementById("loginMessage").textContent="Invalid demo credentials.";return}currentUser={...u,email};localStorage.setItem("terrasync_demo_user",email);document.getElementById("loginScreen").hidden=true;document.getElementById("appShell").hidden=false;document.getElementById("userName").textContent=u.name;document.getElementById("userRole").textContent=u.role;document.getElementById("userInitials").textContent=initials(u.name);renderProfile();});
document.getElementById("logoutButton").addEventListener("click",()=>{localStorage.removeItem("terrasync_demo_user");location.reload()});
document.querySelectorAll("#mainNav [data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
document.querySelectorAll("[data-view-link]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.viewLink)));
document.querySelectorAll("[data-action='start-inspection']").forEach(b=>b.addEventListener("click",()=>showView("inspect")));
document.body.addEventListener("click",e=>{const b=e.target.closest("[data-start]");if(b){document.getElementById("workOrder").value=b.dataset.start;showView("inspect")}});

document.getElementById("startCameraButton").addEventListener("click",async()=>{capturedEvidence=null;document.getElementById("submitInspectionButton").disabled=true;document.getElementById("capturedPreview").hidden=true;if(await openCam(document.getElementById("cameraPreview"),"inspection"))document.getElementById("captureButton").disabled=false;});
document.getElementById("captureButton").addEventListener("click",async()=>{const status=document.getElementById("captureMetadata");try{status.textContent="Capturing GPS, time and image…";capturedEvidence=await makeEvidence(document.getElementById("cameraPreview"),document.getElementById("captureCanvas"));stopCamera();const img=document.getElementById("capturedPreview");img.src=`data:${capturedEvidence.mime_type};base64,${capturedEvidence.content_base64}`;img.hidden=false;document.getElementById("cameraPreview").hidden=true;document.getElementById("retakeButton").hidden=false;document.getElementById("submitInspectionButton").disabled=false;document.getElementById("evidenceStatus").textContent="Verified";document.getElementById("evidenceStatus").className="status good";status.textContent=`${new Date(capturedEvidence.captured_at).toLocaleString()} · ${capturedEvidence.latitude.toFixed(6)}, ${capturedEvidence.longitude.toFixed(6)} · ±${Math.round(capturedEvidence.accuracy_m)} m`; }catch(e){status.textContent=e.message}});
document.getElementById("retakeButton").addEventListener("click",()=>document.getElementById("startCameraButton").click());

document.getElementById("openAssetCamera").addEventListener("click",async()=>{capturedAssetEvidence=null;document.getElementById("assetPreview").hidden=true;if(await openCam(document.getElementById("assetCamera"),"asset"))document.getElementById("captureAssetPhoto").disabled=false;});
document.getElementById("captureAssetPhoto").addEventListener("click",async()=>{const st=document.getElementById("assetCaptureStatus");try{st.textContent="Capturing verified asset photo…";capturedAssetEvidence=await makeEvidence(document.getElementById("assetCamera"),document.getElementById("assetCanvas"));stopAssetCamera();const img=document.getElementById("assetPreview");img.src=`data:${capturedAssetEvidence.mime_type};base64,${capturedAssetEvidence.content_base64}`;img.hidden=false;document.getElementById("assetCamera").hidden=true;document.getElementById("retakeAssetPhoto").hidden=false;st.textContent=`Captured ${new Date(capturedAssetEvidence.captured_at).toLocaleString()} · ${capturedAssetEvidence.latitude.toFixed(6)}, ${capturedAssetEvidence.longitude.toFixed(6)}`;}catch(e){st.textContent=e.message}});
document.getElementById("retakeAssetPhoto").addEventListener("click",()=>document.getElementById("openAssetCamera").click());

document.getElementById("assetForm").addEventListener("submit",e=>{e.preventDefault();if(!capturedAssetEvidence){document.getElementById("assetCaptureStatus").textContent="A live camera photo is required.";return}state.assets.unshift({id:uid(),type:document.getElementById("assetType").value,manufacturer:document.getElementById("assetManufacturer").value,model:document.getElementById("assetModel").value,serial:document.getElementById("assetSerial").value,quantity:+document.getElementById("assetQuantity").value||1,height:document.getElementById("assetHeight").value,dimensions:document.getElementById("assetDimensions").value,condition:document.getElementById("assetCondition").value,position:document.getElementById("assetPosition").value,notes:document.getElementById("assetNotes").value,source:"Created on-site",evidence:capturedAssetEvidence});saveAssets();e.target.reset();document.getElementById("assetQuantity").value=1;capturedAssetEvidence=null;document.getElementById("assetPreview").hidden=true;document.getElementById("assetCaptureStatus").textContent="Asset added. Capture required for next new asset.";});

document.getElementById("inspectionForm").addEventListener("submit",async e=>{e.preventDefault();const wo=state.workOrders.find(w=>w.id===document.getElementById("workOrder").value);if(!wo||!capturedEvidence){document.getElementById("formMessage").textContent="Verified camera evidence is required.";return}const payload={client_id:uid(),work_order_id:wo.id,site_id:wo.site_id,inspector_name:currentUser.name,report_type:document.getElementById("templateSelect").value,summary:document.getElementById("observations").value,answers:{structural_condition:document.getElementById("structural").value,electrical_condition:document.getElementById("electrical").value,safety_condition:document.getElementById("safety").value,overall_grade:document.getElementById("grade").value,earth_resistance_ohm:document.getElementById("earth").value||null,temperature_c:document.getElementById("temperature").value||null,observations:document.getElementById("observations").value,asset_inventory:state.assets.map(a=>({type:a.type,manufacturer:a.manufacturer,model:a.model,serial:a.serial,quantity:a.quantity,height:a.height,condition:a.condition,position:a.position}))},evidence:[capturedEvidence],latitude:capturedEvidence.latitude,longitude:capturedEvidence.longitude,captured_at:capturedEvidence.captured_at,submit:true};state.outbox.push({mutation_id:uid(),entity:"report",operation:"upsert",payload});saveOutbox();document.getElementById("formMessage").textContent="Inspection saved and queued.";capturedEvidence=null;document.getElementById("submitInspectionButton").disabled=true;await syncOutbox();showView("reports")});
async function syncOutbox(){if(!navigator.onLine){alert("Offline. Queue retained on this device.");return}if(!state.outbox.length){await loadData();return}const r=await api("/sync/push",{method:"POST",body:JSON.stringify({mutations:state.outbox})});const body=await r.json();const done=new Set(body.results.filter(x=>["applied","duplicate"].includes(x.status)).map(x=>x.mutation_id));state.outbox=state.outbox.filter(x=>!done.has(x.mutation_id));saveOutbox();await loadData();}
document.getElementById("syncButton").addEventListener("click",syncOutbox);
window.addEventListener("online",()=>{setNetwork();syncOutbox()});window.addEventListener("offline",setNetwork);
if("serviceWorker" in navigator)navigator.serviceWorker.register("/app/service-worker.js");
const remembered=localStorage.getItem("terrasync_demo_user");if(remembered&&demoUsers[remembered]){document.getElementById("loginEmail").value=remembered;document.getElementById("loginPassword").value="demo123";document.getElementById("loginForm").requestSubmit()}
setNetwork();hydrate();loadData().catch(()=>{});