from datetime import datetime, timezone
from io import BytesIO
import base64

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import AIFinding, InspectionReport, Site, WorkOrder


def build_report_pdf(db: Session, report: InspectionReport) -> bytes:
    """Render a coordinator-ready inspection PDF with evidence and AI findings."""
    site = db.get(Site, report.site_id)
    work_order = db.get(WorkOrder, report.work_order_id)
    findings = list(
        db.scalars(
            select(AIFinding)
            .where(AIFinding.report_id == report.id)
            .order_by(AIFinding.created_at)
        )
    )

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=report.report_no,
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph("TerraSync Field Inspection Report", styles["Title"]),
        Paragraph(report.report_no, styles["Heading2"]),
        Spacer(1, 6),
    ]

    metadata = [
        ["Site", f"{site.code} — {site.name}" if site else report.site_id],
        ["Work order", work_order.work_order_no if work_order else report.work_order_id],
        ["Inspector", report.inspector_name],
        ["Type", report.report_type],
        ["Status", report.status],
        ["Captured", str(report.captured_at or "Not supplied")],
        ["GPS", f"{report.latitude}, {report.longitude}" if report.latitude is not None else "Not supplied"],
        ["AI risk score", f"{report.ai_risk_score}/100"],
    ]
    table = Table(metadata, colWidths=[38 * mm, 130 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.extend([table, Spacer(1, 12)])

    story.append(Paragraph("Summary", styles["Heading2"]))
    story.append(Paragraph(report.summary or "No summary supplied.", styles["BodyText"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("Inspection responses", styles["Heading2"]))
    answer_rows = [["Field", "Value"]]
    answer_rows.extend(
        [[key.replace("_", " ").title(), str(value)] for key, value in sorted((report.answers or {}).items())]
    )
    answers_table = Table(answer_rows, colWidths=[65 * mm, 103 * mm], repeatRows=1)
    answers_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.extend([answers_table, Spacer(1, 10)])

    story.append(Paragraph("AI-assisted pre-screen", styles["Heading2"]))
    story.append(Paragraph(report.ai_summary or "Not screened.", styles["BodyText"]))
    finding_rows = [["Severity", "Finding", "Detail"]]
    if findings:
        finding_rows.extend([[f.severity, f.title, f.detail] for f in findings])
    else:
        finding_rows.append(["—", "No findings", "No flags were generated by the pre-screening engine."])
    finding_table = Table(finding_rows, colWidths=[24 * mm, 52 * mm, 92 * mm], repeatRows=1)
    finding_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.extend([finding_table, Spacer(1, 10)])

    story.append(Paragraph("Verified camera evidence", styles["Heading2"]))
    evidence_rows = [["Source", "Capture", "SHA-256"]]
    for item in report.evidence or []:
        evidence_rows.append([
            item.get("source", ""),
            f"{item.get('captured_at', '')} | {item.get('latitude', '')}, {item.get('longitude', '')}",
            item.get("sha256") or "Not supplied",
        ])
        encoded = item.get("content_base64")
        if encoded:
            try:
                image_bytes = base64.b64decode(encoded)
                image = Image(BytesIO(image_bytes))
                image._restrictSize(168 * mm, 95 * mm)
                story.extend([Spacer(1, 6), image, Spacer(1, 8)])
            except Exception:
                pass
    if len(evidence_rows) == 1:
        evidence_rows.append(["—", "No verified camera evidence", "—"])
    evidence_table = Table(evidence_rows, colWidths=[28 * mm, 70 * mm, 70 * mm], repeatRows=1)
    evidence_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.extend([evidence_table, Spacer(1, 12)])

    generated = datetime.now(timezone.utc).isoformat()
    story.append(
        Paragraph(
            f"Generated by TerraSync on {generated}. AI findings are pre-screening aids and require human review.",
            styles["Italic"],
        )
    )
    doc.build(story)
    return buffer.getvalue()
