"""baseline_m1_m4

Revision ID: 9cd04b809439
Revises: 
Create Date: 2026-09-01 12:01:57.218040
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9cd04b809439'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('staff_no', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activation_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activation_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activation_codes_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_name', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('device_key', sa.String(length=120), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_key'), ['device_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_token_fingerprint'), ['token_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_code'), ['code'], unique=True)

    op.create_table('template_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_definitions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_definitions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_definitions_slug'), ['slug'], unique=True)

    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_sessions_token_fingerprint'), ['token_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_web_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_no', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_work_order_no'), ['work_order_no'], unique=True)

    op.create_table('ai_rule_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_rule_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_rule_sets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_rule_sets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_rule_sets_template_id'), ['template_id'], unique=False)

    op.create_table('asset_schemas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('evidence_rules', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_schemas_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_schemas_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_schemas_project_id'), ['project_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('height_or_elevation', sa.String(length=120), nullable=True),
    sa.Column('dimensions', sa.String(length=160), nullable=True),
    sa.Column('position', sa.String(length=160), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('inspection_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('report_no', sa.String(length=80), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('inspector_name', sa.String(length=120), nullable=False),
    sa.Column('report_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('ai_status', sa.String(length=50), nullable=False),
    sa.Column('ai_risk_score', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_reports_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_reports_report_no'), ['report_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_reports_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_reports_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('report_layouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('compression_profile', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_layouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_layouts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_layouts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_layouts_template_id'), ['template_id'], unique=False)

    op.create_table('template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_versions_template_id'), ['template_id'], unique=False)

    op.create_table('ai_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_findings_report_id'), ['report_id'], unique=False)

    op.create_table('defects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_report_id'))

    op.drop_table('defects')
    with op.batch_alter_table('ai_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_findings_report_id'))

    op.drop_table('ai_findings')
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_versions_template_id'))

    op.drop_table('template_versions')
    with op.batch_alter_table('report_layouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_layouts_template_id'))
        batch_op.drop_index(batch_op.f('ix_report_layouts_project_id'))
        batch_op.drop_index(batch_op.f('ix_report_layouts_client_id'))

    op.drop_table('report_layouts')
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_reports_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_reports_site_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_reports_report_no'))
        batch_op.drop_index(batch_op.f('ix_inspection_reports_client_id'))

    op.drop_table('inspection_reports')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_assets_site_id'))
        batch_op.drop_index(batch_op.f('ix_assets_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_assets_client_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    with op.batch_alter_table('asset_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_schemas_project_id'))
        batch_op.drop_index(batch_op.f('ix_asset_schemas_client_id'))
        batch_op.drop_index(batch_op.f('ix_asset_schemas_asset_type'))

    op.drop_table('asset_schemas')
    with op.batch_alter_table('ai_rule_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_rule_sets_template_id'))
        batch_op.drop_index(batch_op.f('ix_ai_rule_sets_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_rule_sets_client_id'))

    op.drop_table('ai_rule_sets')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_work_order_no'))
        batch_op.drop_index(batch_op.f('ix_work_orders_site_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_assigned_user_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_token_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_expires_at'))

    op.drop_table('web_sessions')
    with op.batch_alter_table('template_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_definitions_slug'))
        batch_op.drop_index(batch_op.f('ix_template_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_template_definitions_client_id'))

    op.drop_table('template_definitions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_code'))
        batch_op.drop_index(batch_op.f('ix_projects_client_id'))

    op.drop_table('projects')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_token_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_devices_device_key'))

    op.drop_table('devices')
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activation_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_activation_codes_expires_at'))

    op.drop_table('activation_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_code'))

    op.drop_table('sites')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_code'))

    op.drop_table('clients')
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_change_events_entity_id'))

    op.drop_table('change_events')
    # ### end Alembic commands ###
